# Discovery server access
#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8761/eureka/
  #instance:
   # leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
